### ISSUE TITLE
Scalelite-nginx by Docker-compose

### ISSUE THREAD

**Issue by ntatgss** [blindsidenetworks/scalelite#164]
Hello, I install Scalelite using Docker-compose, this is my part about Scalelite-nginx

```
scalelite-nginx:
    image: blindsidenetwks/scalelite:v1-nginx
    restart: on-failure
    container_name: scalelite-nginx
    env_file: /etc/default/scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
    volumes:
      - /mnt/scalelite-recordings/var/bigbluebutton/published:/var/bigbluebutton/published
      - /etc/letsencrypt:/etc/nginx/ssl:ro
```
And I ran into error that docker can not find /etc/nginx/live.....

When I do run this to see what's inside the /etc/nginx/ssl of the docker:

`docker cp scalelite-nginx:/etc/nginx/ssl ~/nginx`

I got this:

> Error: No such container:path: scalelite-nginx:/etc/nginx/ssl

How can I configure ssl for Scalelite-nginx using letsencrypt?
