### ISSUE TITLE
Add rake task to sync (not just add) servers defined in a YAML file

### ISSUE THREAD

**Issue by defnull** [blindsidenetworks/scalelite#644]
For automated deployment, it would be extremely helpful to be able to get a scalelite cluster into a desired state based on a simple configuration file. The `servers:addAll` tasks goes into the right direction, but it is not able do modify or remove servers. The idea would be to have a rake task named `servers:sync[file]` that reads a YAML file given the following syntax:

```yaml
servers:
    <server-id>:
        secret: "required"
        url: # default: "https://<server-id>/bigbluebutton/api"
        enabled: # default: true
        load_multiplier: # default: 1.0

    # Example for a simple server (ID equals hostname)
    bbb1.example.com:
        secret: "1bdce5cbab581f3f20b199b970e53ae3c9d9df6392f79589bd58be020ed14535"

    # Example for a legacy server (generated ID) and some non-default settings
    02bff3a7-c95f-49d3-b1e5-c53eddd4dd68:
        secret: "2bdce5cbab581f3f20b199b970e53ae3c9d9df6392f79589bd58be020ed14535"
        url: "https://bbb1.example.com/bigbluebutton/api"
        enabled: false
        load_multiplier: 5.0
```

The task would read the YAML file and add/remove/modify servers according to the desired cluster state. More precisely, it would:

* Add missing servers to the cluster.
* Remove undesired servers from the cluster, panicking them first if necessary.
* Cordon servers that are enabled but should be disabled.
* Enable servers that are cordoned or disabled but should be enabled.
* Update secret or load_multiplier if necessary.

I already implemented all this with a small python script using existing rake tasks or `bin/rails runner` snippets. It should be even easier to do in a rake task, but I am not a ruby developer, so I'd need some help with that. Anyone willing to help?
