### ISSUE TITLE
Refactoring required

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/scalelite#709]
After updating rubocop to a newer version and changing the rules applied we found bolted code and some other bad practices that should be fixed. The rubocop rules where partially disabled for the moment, but they need to be restored ASAP.

If we want to improve the quality of code we would have to work on:

```
Metrics/PerceivedComplexity:
  Max: 17
  Exclude:
    - app/models/recording.rb
    - app/models/server.rb
    - lib/server_sync.rb

Metrics/AbcSize:
  Max: 60
  Exclude:
    - app/controllers/bigbluebutton_api_controller.rb
    - app/models/recording.rb
    - app/models/server.rb
    - lib/recording_importer.rb
    - lib/server_sync.rb

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - app/models/recording.rb
    - app/models/server.rb
    - lib/server_sync.rb

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/bigbluebutton_api_controller.rb

Naming/PredicateName:
  Exclude:
    - app/controllers/bigbluebutton_api_controller.rb

Style/CombinableLoops:
  Exclude:
    - lib/server_sync.rb
    - test/models/server_test.rb
```
