### ISSUE TITLE
Docker-Compose?

### ISSUE THREAD

**Issue by einhirn** [blindsidenetworks/scalelite#83]
Hi, when starting to setup scalelite, I thought that it would have been nice to have a tarball of the systemd service files so I wouldn't need to copy&paste them to my system...

I finally went with docker-compose, so I didn't need the files you provided, but maybe someone else would like that, too.

**Comment by aakatev** [comment]
Off topic, but do you mind sharing docker-compose file?

**Comment by einhirn** [comment]
Not at all... This combines everything needed - the scalelite containers, redis, postgres, greenlight (using 'customize' instructions). I needed to modify the 'greenlight.nginx' file a little (nginx does a longest match for locations, so greenlight's '/b' erroneously matched '/bigbluebutton', too. Adding a trailing slash to the location helped, it works fine now. Oh, and I linked scalelites Environment file to `.env` because of the variables used in Volumes etc.

Using "restart: unless-stopped" makes the containers reappear after a reboot, so I actually don't need any service files. But I lose a bit flexibility to restart e.g. greenlight after a config change without restarting scalelite, too. Reloading the Env file usually takes `docker-compose down` followed by a `... up (-d) ` afterwards - except when you try to `source` the env-file before reloading a container...

```yaml
version: '3'

services:
  greenlight:
    entrypoint: [bin/start]
    image: greenlight-local:release-v2
    container_name: greenlight-v2
    env_file: /etc/default/greenlight
    restart: unless-stopped
    volumes:
      - /var/log/greenlight:/usr/src/app/log
    depends_on:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=very_secret
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - /opt/redis:/data
  scalelite-api:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-api
    container_name: scalelite-api
    restart: unless-stopped
    env_file: /etc/default/scalelite
    volumes:
      - ${SCALELITE_RECORDING_DIR}:/var/bigbluebutton
    depends_on:
      - db
      - redis
  scalelite-nginx:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx
    restart: unless-stopped
    container_name: scalelite-nginx
    env_file: /etc/default/scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
    volumes:
      - ${SCALELITE_RECORDING_DIR}/published:/var/bigbluebutton/published
      - /etc/ssl:/etc/nginx/ssl:ro
      - /opt/greenlight/greenlight-env.nginx:/etc/bigbluebutton/nginx/greenlight-env.nginx
    ports:
      - "80:80"
      - "443:443"
  scalelite-poller:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-poller
    container_name: scalelite-poller
    restart: unless-stopped
    env_file: /etc/default/scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
  scalelite-recording-importer:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer
    container_name: scalelite-recording-importer
    restart: unless-stopped
    env_file: /etc/default/scalelite
    volumes:
      - ${SCALELITE_RECORDING_DIR}:/var/bigbluebutton
    depends_on:
      - scalelite-api
      - db
      - redis
```
